version: "3.8"

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Radmilo1234
      MYSQL_DATABASE: newsdb
      MYSQL_PASSWORD: Radmilo1234
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www/NewsApplication
    depends_on:
      - database
